name:         stochmodgroup
description:  Reading Group on Stochastic Modelling, at Ca' Foscari University of Venice
url:          https://matteoiacopini.github.io/stochmodgroup/


theme: jekyll-theme-architect

plugins:
  - jekyll-feed