name:         stochmodgroup
description:  Reading Group on Stochastic Modelling, at Ca' Foscari University of Venice
url:          https://matteoiacopini.github.io/stochmodgroup/


theme: jekyll-theme-architect

show_downloads: true

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings